version: '3.7'

services:
  dev:
    build: ./
    container_name: dev
    ports:
      - '1234:1234'
    volumes:
      - '~/development:/home/docker/development'
      - '~/.ssh:/home/docker/.ssh'
      - 'dev-box:/home/docker'

volumes:
  dev-box:
