---
# NeoVim role main tasks

- name: Create directory for vim-plug
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug for neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

- name: nvim config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    recurse: true

- name: nvim init file
  template:
    src: init.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Install nvim dependencies
  command: nvim --headless +PlugInstall +qall
  args:
    creates: "{{ ansible_env.HOME }}/.local/shared/nvim/site/plugged/vim/autoload/dracula.vim"