# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Windows Subsystem for Linux (WSL 1) specific configuration

# Stop z nice priority change process on WSL
#unsetopt BG_NICE

# Tmux and Terminal colors
#export TERM=screen-256color
#[ -n "$TMUX" ] && export TERM=screen-256color
#alias tmux='TERM=screen-256color tmux -2'

# END Windows Subsystem for Linux (WSL 1)

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="mh"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git z npm)

export EDITOR="vim"

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#

# Aliases
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

git_fuzzy_checkout() {
  local branches branch
  branches=$(git branch -a) &&
  branch=$(echo "$branches" | fzf +s +m -e) &&
  git checkout $(echo "$branch" | sed "s:.* remotes/origin/::" | sed "s:.* ::")
}

alias git-checkout-fuzzy="git_fuzzy_checkout"

alias git-delete-merged-branches='git branch --merged >/tmp/merged-branches && vi /tmp/merged-branches && xargs git branch -D </tmp/merged-branches'
alias git-delete-all-branches='git branch >/tmp/merged-branches && vi /tmp/merged-branches && xargs git branch -D </tmp/merged-branches'

alias md5sum='md5 -r'

git-rebase-master() {
  git checkout -b $1 && git checkout $1 && git branch -D master && git checkout master && git pull && git checkout $1 && git rebase master && git checkout master && git rebase $1
}

git-rebase-develop() {
  git checkout -b $1 && git checkout $1 && git branch -D develop && git checkout develop && git pull && git checkout $1 && git rebase develop && git checkout develop && git rebase $1
}

# Review a github PR using the GH cli
# Checkout to branch and approve and merge (if branch provided)
# If no branch provided it expect that you're already checked out to the branch
review-merge-pr () {
  if [ ! -z $1 ];
    then
      gh pr checkout $1
    fi
  gh pr review --comment -b "Reviewed & Approved"
  gh pr review --approve
  gh pr merge --merge --delete-branch
}

send-to-nas() {
  rsync -aP $1 nas:/mnt/public/$2
}

# Change git GPG signature and email from personal to work
alias git-signature-work='git config --global user.signingkey <YOUR_WORK_SIGNING_KEY> && git config --global user.email <YOUR_WORK_EMAIL>'
alias git-signature-personal='git config --global user.signingkey <YOUR_PERSONAL_SIGNING_KEY> && git config --global user.email <YOUR_PERSONAL_EMAIL>'

{% if os == "linux" -%}
{% if wsl|bool %}
pbcopy () {
  tee <&0 | clip.exe
  exit 0
}

pbpaste () {
  powershell.exe Get-Clipboard | sed 's/\r$//' | sed -z '$ s/\n$//'
  exit 0
}
{% else %}
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
{% endif -%}
{% endif -%}

{% if os == "macos" %}
# Mac specific aliases

# Use brew's git and not apple git
alias git='/usr/local/bin/git'

alias md5sum="md5 -r"

# END Mac specific aliases
{% endif -%}

# END Aliases

# Fix gpg signing -- Tell gpg which tty
export GPG_TTY=$(tty)

# pyenv
export PATH="$HOME/.pyenv/bin:$HOME/.local/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# END pyenv

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# END nvm

# goenv
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
eval "$(goenv init -)"
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
# END goenv

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
# END jenv

source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
