---
- name: Install git-fire
  get_url:
    url: https://raw.githubusercontent.com/qw3rtman/git-fire/refs/heads/master/git-fire
    dest: "{{ ansible_env.HOME }}/.local/bin/git-fire"
    mode: "0755"

- name: Install git-open
  get_url:
    url: https://raw.githubusercontent.com/paulirish/git-open/refs/heads/master/git-open
    dest: "{{ ansible_env.HOME }}/.local/bin/git-open"
    mode: "0755"

- name: Clone diff-so-fancy repository
  git:
    repo: https://github.com/so-fancy/diff-so-fancy.git
    dest: "{{ ansible_env.HOME }}/.local/share/diff-so-fancy"
    version: next
    depth: 1

- name: Create symlink for diff-so-fancy executable
  file:
    src: "{{ ansible_env.HOME }}/.local/share/diff-so-fancy/diff-so-fancy"
    dest: "{{ ansible_env.HOME }}/.local/bin/diff-so-fancy"
    state: link

- name: Configure git pager for diff-so-fancy
  git_config:
    name: core.pager
    value: "diff-so-fancy | less --tabs=4 -RF"
    scope: global

- name: Configure git interactive diff filter
  git_config:
    name: interactive.diffFilter
    value: "diff-so-fancy --patch"
    scope: global

- name: Enable git color UI
  git_config:
    name: color.ui
    value: "true"
    scope: global

- name: Configure diff-highlight colors
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "color.diff-highlight.oldNormal", value: "red bold" }
    - { name: "color.diff-highlight.oldHighlight", value: "red bold 52" }
    - { name: "color.diff-highlight.newNormal", value: "green bold" }
    - { name: "color.diff-highlight.newHighlight", value: "green bold 22" }
    - { name: "color.diff.meta", value: "11" }
    - { name: "color.diff.frag", value: "magenta bold" }
    - { name: "color.diff.func", value: "146 bold" }
    - { name: "color.diff.commit", value: "yellow bold" }
    - { name: "color.diff.old", value: "red bold" }
    - { name: "color.diff.new", value: "green bold" }
    - { name: "color.diff.whitespace", value: "red reverse" }
