---
- hosts: all

  vars:
    sql_server_deps: false
    skip_install_python: false
    python_version: "latest"
    skip_install_node: false
    node_version: "latest"
    os: linux
    wsl: false
    common_dependencies:
      - curl
      - fzf
      - git
      - jq
      - neovim
      - tmux
      - tree
      - tree
      - vim
      - wget
      - zsh
    apt_dependencies:
      - silversearcher-ag
      # database drivers
      - libpq-dev
      - unixodbc-dev
      # if sql_server_deps is truthy, add ms sql server deps
      - "{{ sql_server_deps | bool | ternary('msodbcsql17', '') }}"
      - "{{ sql_server_deps | bool | ternary('mssql-tools', '') }}"
      # for building python
      - build-essential
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - python3-openssl
      - zlib1g-dev
      # Redis cli
      - redis-tools
    brew_dependencies:
      - the_silver_searcher
      # database drivers
      - libpq
      - unixodbc
      # for building python
      - coreutils
      - zlib

  tasks:
    - name: Add microsoft packages key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: yes
      when: sql_server_deps | bool

    - name: Add mssql packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/18.04/prod.list
        dest: /etc/apt/sources.list.d/mssql-release.list
      become: yes
      when: sql_server_deps | bool

    - name: APT Install dependencies
      when: not os == "macos"
      apt:
        pkg: "{{ common_dependencies + apt_dependencies|select|list }}"
        state: present
      become: yes
      environment:
        ACCEPT_EULA: Y

    - name: Brew install dependencies
      community.general.homebrew:
        pkg: "{{ common_dependencies + brew_dependencies }}"
        state: present
      when: os == "macos"

    - name: Install asdf
      git:
        repo: https://github.com/asdf-vm/asdf.git
        version: v0.14.0
        depth: 2
        dest: "{{ ansible_env.HOME }}/.asdf"

    - name: Install asdf python plugin
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add python"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/plugins/python"

    - name: Install asdf NodeJS plugin
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add nodejs"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/plugins/nodejs"

    - name: Install asdf golang plugin
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add golang"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/plugins/golang"

    - name: Install asdf Java plugin
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add java"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/plugins/java"

    - name: Install asdf Terraform plugin
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add terraform"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/plugins/terraform"

    - name: Install asdf aws-cli plugin
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf plugin add awscli"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/plugins/awscli"

    - name: Install python {{ python_version }}
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf install python {{ python_version }} && {{ ansible_env.HOME }}/.asdf/bin/asdf global python {{ python_version }}"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/installs/python"
      when: not skip_install_python | bool

    - name: Install NodeJS {{ node_version }}
      command: "{{ ansible_env.HOME }}/.asdf/bin/asdf install nodejs {{ node_version }} && {{ ansible_env.HOME }}/.asdf/bin/asdf global node {{ node_version }}"
      args:
        creates: "{{ ansible_env.HOME }}/.asdf/installs/nodejs"
      when: not skip_install_python | bool

    - name: Install oh-my-zsh
      git:
        depth: 2
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: Install zsh syntax highlight
      git:
        depth: 2
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/zsh-syntax-highlighting"

    - name: Install z
      get_url:
        url: https://raw.githubusercontent.com/rupa/z/master/z.sh
        dest: "{{ ansible_env.HOME }}"

    - name: zshrc
      template:
        src: ./templates/zshrc
        dest: "{{ ansible_env.HOME }}/.zshrc"

    - name: Create vim themes path
      file:
        path: "{{ ansible_env.HOME }}/.vim/colors"
        state: directory

    - name: Download vim monokai
      get_url:
        url: https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim
        dest: "{{ ansible_env.HOME }}/.vim/colors"

    - name: vimrc
      copy:
        src: ./templates/vimrc
        dest: "{{ ansible_env.HOME }}/.vimrc"

    # NeoVim configuration

    - name: Create directory for vim-plug
      file:
        path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
        state: directory

    - name: Install vim-plug for neovim
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

    - name: nvim config dir
      file:
        path: "{{ ansible_env.HOME }}/.config/nvim"
        state: directory
        recurse: true

    - name: nvim init file
      copy:
        src: ./templates/init.vim
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

    - name: Install nvim dependencies
      command: nvim --headless +PlugInstall +qall
      args:
        creates: "{{ ansible_env.HOME }}/.local/shared/nvim/site/plugged/vim/autoload/dracula.vim"

    # END NeoVim configuration

    - name: tmux config
      copy:
        src: ./templates/tmux.conf
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
...
